# Generated by Django 4.2.1 on 2023-05-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_schoolwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schoolwork',
            new_name='Document',
        ),
    ]
