# Generated by Django 4.2.1 on 2023-06-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedded_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='year_level',
            field=models.PositiveIntegerField(),
        ),
    ]
