# Generated by Django 4.2.1 on 2023-06-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_document_embedded_url_alter_document_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('PUBLISHER', 'publisher')], default='student', max_length=64),
        ),
    ]
