# Generated by Django 4.2.1 on 2023-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
