# Generated by Django 4.2.1 on 2023-06-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
